import os

block_cipher = None

a = Analysis(
    ['main_windows.py'],
    pathex=[os.path.dirname(os.path.abspath('main_windows.py'))], 
    binaries=[],
    datas=[
        ('icon', 'icon'),  
        ('chip/chip_point.csv', 'chip'),
    ],
    hiddenimports=[
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
        'pyqtgraph',
        'numpy',
        'pandas',
        'openpyxl',
        'openpyxl.workbook',
        'openpyxl.workbook.workbook',
        'openpyxl.worksheet',
        'openpyxl.worksheet.worksheet',
        'openpyxl.cell',
        'openpyxl.cell.cell',
        'serial',
        'serial.tools.list_ports',
        'cv2', 
        'main_window', 
        'main_window.ui2', 
        'chip', 
        'chip.DMF_Chip',
        'chip.chip_layout',
        'serial_driver', 
        'serial_driver.Serialdriver', 
        'cam', 
        'cam.cam_module', 
        'logger', 
        'logger.log', 
        'utils',
        'utils.path_helper', 
        'dateutil', 
        'dateutil.parser', 
        'dateutil.relativedelta', 
        'dateutil.tz', 
        'secrets', 
        'numpy.random',
        'numpy.random._pickle',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'pytest',
        'unittest',
        'doctest',
        'test',
        'tests',
        'tkinter',
        'tkinter.*',
        'tcl',
        'IPython',
        'jupyter',
        'notebook',
        'pdb',
        'setuptools',
        'distutils',
        'http',
        'urllib3',
        'requests',
        'sqlite3',
        'xmlrpc',
        'email',
        'scipy',
        'cryptography',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,  
    name='DMF_Driver', 
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,  # 如果未安装UPX，设置为False避免错误
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False, 
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon/dmf.png' if os.path.exists('icon/dmf.png') else None, 
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas, 
    strip=False,
    upx=False,  # 如果未安装UPX，设置为False避免错误
    upx_exclude=[],
    name='玻璃基驱动线路板专用驱动器 V2.1.0',  
)
